fix(build): use python:3.11 instead of python:3.11-alpine
fix an issue where some couldn't get `cffi` installed

```
building '_cffi_backend' extension
gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DFFI_BUILDING=1
-I/usr/include/ffi -I/usr/include/libffi -I/app/.venv/include
-I/usr/local/include/python3.11 -c c/_cffi_backend.c -o
build/temp.linux-aarch64-cpython-311/c/_cffi_backend.o
error: command 'gcc' failed: No such file or directory
```

ref https://github.com/dailymotion/demo-stream-urls-server/issues/6